# Create two numpy array one with integer datatype and another one with float datatype but for both arrays use list to create -> [10,20,30,40,50]

In [4]:
import numpy as np

list = [10,20,30,40,50]

In [ ]:
arr1 = np.array(list, dtype=int) # it changes the array type to integer
print(arr1)
print(arr1.dtype) # it prints the datatype of the array.

[10 20 30 40 50]
int64


In [ ]:
arr2 = np.array(list, dtype=float) # it changes the datatype of list to into list
print(arr2)
print(arr2.dtype)

[10. 20. 30. 40. 50.]
float64


# Create numpy array with having zero,two,three,four dimensions and for  all the array print the dimension and shape and size

In [ ]:
# creating 0D array
arr_0d = np.array(4)
print(arr_0d)
print(arr_0d.ndim)
print(arr_0d.shape)
print(arr_0d.size)

# creating 2D array
arr_2d = np.array([[1,2,3,4], [5,6,7,8]])
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.size)

# creating 3D array
arr_3d = np.array([[[1,2,3,4], [2,3,4,5]], [[3,4,5,6], [4,5,6,7]]])
print(arr_3d)
print(arr_3d.ndim)
print(arr_3d.shape) # (group, rows, column)
print(arr_3d.size)

# creating 4D array
arr_4d = np.array([[[[1,2,3,4], [2,3,4,5]], [[3,4,5,6], [4,5,6,7]]], [[[1,2,3,4], [2,3,4,5]], [[3,4,5,6], [4,5,6,7]]]])
print(arr_4d)
print(arr_4d.ndim)
print(arr_4d.shape) # (group, subgroup, rows, columns)
print(arr_4d.size)

# Create a 1D, 2D, 3D array using arange function

In [ ]:
# 1D array
arr1D = np.arange(6)
print(arr1D)
print(arr1D.ndim)
print(arr1D.shape)

# 2D array
arr2D = np.arange(12).reshape(3,4)
print(arr2D)
print(arr2D.ndim)
print(arr2D.shape)

# 3D array
arr3D = np.arange(24).reshape(2,3,4)
print(arr3D)
print(arr3D.ndim)
print(arr3D.shape)

[0 1 2 3 4 5]
1
(6,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
(3, 4)


ValueError: cannot reshape array of size 61 into shape (2,3,4)