# Joining and Splitting NumPy Arrays

## Core Concepts

* **Joining:** Combining multiple arrays into a single array.
* **Splitting:** Breaking a single array into multiple smaller arrays.

---

## Key Functions

### Joining Arrays

* `np.concatenate()`: Joins a sequence of arrays along an existing axis.
* `np.stack()`: Joins a sequence of arrays along a **new** axis.
* `np.hstack()`: Stacks arrays horizontally (column-wise).
* `np.vstack()`: Stacks arrays vertically (row-wise).

### Splitting Arrays

* `np.split()`: Splits an array into multiple sub-arrays along a specified axis.
* `np.hsplit()`: Splits an array horizontally (column-wise).
* `np.vsplit()`: Splits an array vertically (row-wise).

In [1]:
# np.stack --- joins the array along a new axis (different from concat)
# np.hstack --- horizontal stack
# np.vstack --- vertical stack
import numpy as np

# np.stack
- np.hstack()
- np.vstack()

In [5]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5],[7,8]])

c = np.vstack((a,b))
d = np.concatenate((a,b))
e = np.hstack((a,b))

print(e.shape)
print(e)

print(d.shape)
print(d)

print(c.shape)
print(c)

(2, 4)
[[1 2 4 5]
 [3 4 7 8]]
(4, 2)
[[1 2]
 [3 4]
 [4 5]
 [7 8]]
(4, 2)
[[1 2]
 [3 4]
 [4 5]
 [7 8]]


In [ ]:
# practice code here

# concatenate = works in existing dimension
# stack = new dimension

In [ ]:
# practice code here

### Equal Array Splitting (`np.split` by Integer)

When dividing an array into $N$ equal parts, pass an **integer** representing the number of equally sized sub-arrays. The total number of elements must be evenly divisible by $N$.

```python
import numpy as np

# Original 1D array (6 elements)
a = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 equal parts and unpack into variables
x, y, z = np.split(a, 3)

print(x)  # [1 2]
print(y)  # [3 4]
print(z)  # [5 6]

In [ ]:
# practice code here

### Unequal Array Splitting (`np.split` by Indices)

When an array cannot be divided into equal parts, pass a **list of index positions** to specify exactly where the split should occur.

```python
import numpy as np

# Original 1D array (5 elements)
a = np.array([1, 2, 3, 4, 5])

# Split at index 2 -> gives elements before index 2, and from index 2 onward
b = np.split(a, [2]) 

print(b)
# Output: [array([1, 2]), array([3, 4, 5])]

In [ ]:
# practice code here

### 2D Array Splitting: `np.hsplit` vs. `np.vsplit`

NumPy provides specialized functions to split 2D arrays across columns (horizontally) or across rows (vertically).

---

#### 1. Horizontal Split (`np.hsplit`)
Splits an array **column-wise** (along `axis=1`). It is equivalent to `np.split(..., axis=1)`.

```python
import numpy as np

# 2x4 matrix
arr = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8]
])

# Split horizontally into 2 equal parts
left, right = np.hsplit(arr, 2)

print("Left:\n", left)
# [[1, 2],
#  [5, 6]]

print("Right:\n", right)
# [[3, 4],
#  [7, 8]]

In [ ]:
# practice code here

### 2. Vertical Split (`np.vsplit`)

Splits an array **row-wise** (along `axis=0`). It is equivalent to `np.split(..., axis=0)`.

```python
# Split vertically into 2 equal parts
top, bottom = np.vsplit(arr, 2)

print("Top:\n", top)
# [[1, 2, 3, 4]]

print("Bottom:\n", bottom)
# [[5, 6, 7, 8]]

In [ ]:
# practice code here

In [ ]:
'''
numpy mathematical and statistical operation

1. sum() --- sum of all element in an array
2. mean() --- average of numbers
3. median() --- middle numbers
4. min() --- lowest element
5. max() --- highest element
6. std() --- standard deviation (how values are far from mean)
7. var() --- how values are far from mean
'''

'\nnumpy mathematical and statistical operation\n\n1. sum()\n2. mean()\n'

# NumPy Mathematical and Statistical Operations

NumPy provides built-in statistical functions to compute aggregates over an entire array or along specific axes (`axis=0` for columns, `axis=1` for rows).

---

### Key Functions Overview

| Function | Method / Syntax | Description |
| :--- | :--- | :--- |
| **Sum** | `np.sum(a)` / `a.sum()` | Sum of all elements in the array. |
| **Mean** | `np.mean(a)` / `a.mean()` | Arithmetic average of elements. |
| **Median** | `np.median(a)` | Middle value in a sorted dataset (requires `np.median()`). |
| **Min** | `np.min(a)` / `a.min()` | Smallest value in the array. |
| **Max** | `np.max(a)` / `a.max()` | Largest value in the array. |
| **Standard Deviation** | `np.std(a)` / `a.std()` | Measure of how spread out numbers are from the mean. |
| **Variance** | `np.var(a)` / `a.var()` | Average of squared differences from the mean ($\text{std} = \sqrt{\text{var}}$). |

---

### Code Example

```python
import numpy as np

# Sample 1D array
data = np.array([10, 20, 30, 40, 50])

print("Sum:       ", np.sum(data))       # 150
print("Mean:      ", np.mean(data))      # 30.0
print("Median:    ", np.median(data))    # 30.0
print("Min:       ", np.min(data))       # 10
print("Max:       ", np.max(data))       # 50
print("Variance:  ", np.var(data))       # 200.0
print("Std Dev:   ", np.std(data))       # 14.1421...

In [ ]:
# practice code here

### NumPy Aggregations Along Axes: `axis=0` vs. `axis=1`

* **`axis=0`**: Operates **down the rows** (vertically, along columns).
* **`axis=1`**: Operates **across the columns** (horizontally, along rows).

---

#### 1. Operations Along `axis=0` (Column-wise)

Collapses rows into a single summary row by computing along each column.

```python
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr)
# [[10 20 30]
#  [40 50 60]]

# Sum down the rows: [10+40, 20+50, 30+60]
print(np.sum(arr, axis=0))
# [50 70 90]
```
### 2. Operations Along `axis=1` (Row-wise)

Collapses columns into a single summary column by computing across each row.

```python
# Sum across the columns: [10+20+30, 40+50+60]
print(np.sum(arr, axis=1))
# [ 60 150]

In [ ]:
# practice code here

In [9]:
arr10 = np.array([[1,2,3, 11],[4,5,6, 11]])
print(arr10)

[[ 1  2  3 11]
 [ 4  5  6 11]]


# NumPy Random Numbers

Used to generate pseudo-random numbers and arrays for scientific computing and simulations.

---

### Common Use Cases

* **Machine Learning:** Initializing weights, splitting datasets, data shuffling.
* **Data Science:** Monte Carlo simulations, generating synthetic data.
* **Testing:** Creating dummy inputs and edge-case testing arrays.
* **Sampling:** Random selection, bootstrapping, permutation testing.

---

### Core Random Functions (`np.random`)

* `np.random.rand()`: Uniformly distributed floats in $[0, 1)$.
* `np.random.randn()`: Standard normally distributed floats ($\mu = 0, \sigma = 1$).
* `np.random.randint(low, high, size)`: Random integers within a range $[low, high)$.
* `np.random.choice(a, size)`: Random sample generated from a given 1D array.

```python
import numpy as np

# Random float array (2 rows, 3 cols) in [0, 1)
print(np.random.rand(2, 3))

# Random integers between 1 and 100 (shape: 4)
print(np.random.randint(1, 100, size=4))

In [ ]:
# practice code here

In [10]:
print(np.random.rand()) # it is used to print random number.

0.3485489035590217


In [11]:
x = np.random.rand()
print(x)

0.7681589942041962


In [12]:
# printing 5 random numbers using np.random.rand
y = np.random.rand(5)
print(y)

[0.08228857 0.4110207  0.89551918 0.89696267 0.48092015]


In [13]:
# generating a random array using np.random.rand

z = np.random.rand(2,3)
print(z)

[[0.67523523 0.92898489 0.45246829]
 [0.12905552 0.57415722 0.51042269]]


In [ ]:
# generating random integer using np.random.randint()

a = np.random.randint(1,10, size=(3,4)) # random integer between 1 to 10
print(y)

In [ ]:
# np.random.choice() --- to select among some given values
b = np.array([10, 20, 30, 40, 50, 60])
c = np.random.choice(a) # chooses a random from array a.
print(c)

d = np.random.choice(a , size = 8) # makes an array of size 8 with some repetition of the elements from a.
print(d)

# using replace = True/False
e = np.random.choice(a, size = 4, replace = False) # here the replace = false means that there will be no error in the code.
print(e)