# 📘 NumPy

### 👨‍💻 Created by Travis Oliphant in 2006

---

## 📂 What is a Library?
A **library** is a collection of pre-written code that helps developers perform tasks without writing everything from scratch.

### 🔑 Uses of NumPy
- Numerical calculations
- Array operations
- Statistics
- Data science applications
- Machine learning workflows


In [2]:
# list
marks = [10, 20, 30, 40]

# 🔢 Array

### 📖 Definition
An **array** is a collection of values of the same data type.

---

## 🧩 ndarray
- Stands for **N-dimensional array**.
- Core data structure in NumPy.
- Supports:
  - Multi-dimensional storage
  - Fast numerical operations
  - Efficient memory usage


In [3]:
import numpy as np
a1 = np.array([10, 20, 30, 40])
print(a1)
print(type(a1))

[10 20 30 40]
<class 'numpy.ndarray'>


In [4]:
l2 = [10, 20, 30, 40]
print(l2)
a2 = np.array(l2)
print(a2)
print(type(a2))

[10, 20, 30, 40]
[10 20 30 40]
<class 'numpy.ndarray'>


# 🔠 dtype

## 📖 Definition
- `dtype` is an **attribute** of a NumPy array.
- It tells you the **type of elements** stored in the array.

---

## 🧩 Example

```python
import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype)   # int64

arr2 = np.array([1.5, 2.5, 3.5])
print(arr2.dtype)  # float64


In [ ]:
a3 = np.array([10, 20, 30, 40])
print(a3*2) # multiplying the array with 2
a4 = np.array([10, 26.9, "amit"])
print(a4)
print(a4.dtype)

[20 40 60 80]
['10' '26.9' 'amit']
<U32


# 📐 ndim

## 📖 Definition
- `ndim` is an **attribute** of a NumPy array.
- It tells you the **number of dimensions** (axes) of the array.

---

## 🧩 Example

```python
import numpy as np

arr1 = np.array([1, 2, 3])
print(arr1.ndim)   # 1 → 1D array

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.ndim)   # 2 → 2D array

arr3 = np.array([[[1], [2]], [[3], [4]]])
print(arr3.ndim)   # 3 → 3D array


In [ ]:
b1 = np.array([[10, 20, 30], [40, 50, 60]])
print(b1) # this will print the 2D array
print(b1.ndim) # this will print the number of dimensions

[[10 20 30]
 [40 50 60]]
2


# 📐 shape

## 📖 Definition
- `.shape` is an **attribute** of a NumPy array.
- It tells you the **size of the array in each dimension**.
- The result is returned as a **tuple**.

---

## 🧩 Example

```python
import numpy as np

# 1D array
a1 = np.array([5, 6, 7, 8])
print(a1.shape)   # (4,) → 4 elements in 1 dimension

# 2D array
a2 = np.array([[5, 6, 7], [9, 10, 11]])
print(a2)
print(a2.shape)   # (2, 3) → 2 rows, 3 columns


In [11]:
a2 = np.array([[5, 6, 7], [9, 10, 11]])
print(a2)
print(a2.shape) # it will tell the shape of the array that is 2x3 and output will be as (2, 3) 

[[ 5  6  7]
 [ 9 10 11]]
(2, 3)


# 🎯 Array Element Indexing in NumPy

## 📖 Definition
- Indexing is used to **access specific elements** in a NumPy array.
- NumPy uses **zero-based indexing** (first element is at index `0`).
- Works for 1D, 2D, and higher-dimensional arrays.

---

## 🧩 Examples

### 1D Array
```python
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr[0])   # 10 → first element
print(arr[2])   # 30 → third element

---
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2[0, 1])   # 2 → element at row 0, column 1
print(arr2[1, 2])   # 6 → element at row 1, column 2

---
arr3 = np.array([[[1, 2], [3, 4]], 
                 [[5, 6], [7, 8]]])
print(arr3[0, 1, 1])   # 4 → first block, second row, second column


In [13]:
b2 = np.array([[5, 6], [9, 10], [12, 13]])
print(b2)
print(b2.shape)
print(b2.ndim) # it will tell the number of dimensions of the array

[[ 5  6]
 [ 9 10]
 [12 13]]
(3, 2)
2


In [16]:
b3 = np.array([[5, 6, 7], [9, 10, 11], [12, 13, 14]])
print(b3)
print(b3.shape)
print(b3.ndim) # it will tell the number of dimensions of the array
print(b3[0, 1]) # it will print the element present at 0th row and 1st column

[[ 5  6  7]
 [ 9 10 11]
 [12 13 14]]
(3, 3)
2
6
