# Create two numpy array one with integer datatype and another one with float datatype but for both arrays use list to create -> [10,20,30,40,50]

In [4]:
import numpy as np

list = [10,20,30,40,50]

In [ ]:
arr1 = np.array(list, dtype=int) # it changes the array type to integer
print(arr1)
print(arr1.dtype) # it prints the datatype of the array.

[10 20 30 40 50]
int64


In [ ]:
arr2 = np.array(list, dtype=float) # it changes the datatype of list to into list
print(arr2)
print(arr2.dtype)

[10. 20. 30. 40. 50.]
float64


# Create numpy array with having zero,two,three,four dimensions and for  all the array print the dimension and shape and size

In [ ]:
# creating 0D array
arr_0d = np.array(4)
print(arr_0d)
print(arr_0d.ndim)
print(arr_0d.shape)
print(arr_0d.size)

# creating 2D array
arr_2d = np.array([[1,2,3,4], [5,6,7,8]])
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)
print(arr_2d.size)

# creating 3D array
arr_3d = np.array([[[1,2,3,4], [2,3,4,5]], [[3,4,5,6], [4,5,6,7]]])
print(arr_3d)
print(arr_3d.ndim)
print(arr_3d.shape) # (group, rows, column)
print(arr_3d.size)

# creating 4D array
arr_4d = np.array([[[[1,2,3,4], [2,3,4,5]], [[3,4,5,6], [4,5,6,7]]], [[[1,2,3,4], [2,3,4,5]], [[3,4,5,6], [4,5,6,7]]]])
print(arr_4d)
print(arr_4d.ndim)
print(arr_4d.shape) # (group, subgroup, rows, columns)
print(arr_4d.size)

# Create a 1D, 2D, 3D array using arange function

In [ ]:
# 1D array
arr1D = np.arange(6)
print(arr1D)
print(arr1D.ndim)
print(arr1D.shape)

# 2D array
arr2D = np.arange(12).reshape(3,4)
print(arr2D)
print(arr2D.ndim)
print(arr2D.shape)

# 3D array
arr3D = np.arange(24).reshape(2,3,4)
print(arr3D)
print(arr3D.ndim)
print(arr3D.shape)

# the rule of reshape is it should be the multiple of the number inside the arange function.

[0 1 2 3 4 5]
1
(6,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2
(3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3
(2, 3, 4)


# slicing

- `threed = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])`
    - i want first 2 elements from first row of first block`(1,2)`
    - `(1,3)`

In [19]:
threed = np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]]])

print(threed)

print(threed[0, 0, 0:2]) 

print(threed[0, 0, [0,2]])

print(threed[0, [0,1], [0,1]])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[1 2]
[1 3]
[1 5]


# Create a numpy array with random integers in between 0 to 50 with size of 25 elements.

In [22]:
rand_arr = np.random.randint(0, 50, size=25)

print(rand_arr)
print(rand_arr.shape)
print(rand_arr.size)

[20 44 42 48  2 17  5 27 48  5  6 29 17  3  8 34 15 29  4  5 31 36  0 11
  1]
(25,)
25


# Create a numpy random float array with range of 0 to 100 with 50 elements

- print first 10 elements.
- print last 10 elements.

In [ ]:
f_array = np.random.uniform(0, 100, size=50) # generates the number in given interla

print(f_array)
print("first 10 elements : ",f_array[0:10])
print("last 10 elements : ", f_array[-10:])

# Do all the mathematical and statistical operation on

- arr ---> [10, 20, 30, 40, 50, 60, 70, 80, 90]

In [ ]:
m_s_op = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print(np.sum(m_s_op))
print(np.average(m_s_op))
print(np.mean(m_s_op))
print(np.median(m_s_op))
print(np.min(m_s_op))
print(np.max(m_s_op))
print(np.std(m_s_op))
print(np.var(m_s_op))

450
50.0
50.0
90
[10 20 30 40 50 60 70 80 90]
[10 20 30 40 50 60 70 80 90]


# YOU GUYS CAN DO YOUR OWN SELF PRACTICE BEFORE CHECKING THE ANSWERS