# 🧊 3D Array

## 📖 Definition
- A **3D array** is a collection of multiple **2D arrays** stacked together.
- Think of it as a **cube of data**:  
  - **Axis 0** → depth (number of 2D arrays stacked)  
  - **Axis 1** → rows  
  - **Axis 2** → columns  

---

## 🧩 Example

```python
import numpy as np

arr3 = np.array([[[1, 2, 3], 
                  [4, 5, 6]],

                 [[7, 8, 9], 
                  [10, 11, 12]]])

print(arr3)
print(arr3.shape)   # (2, 2, 3) → 2 blocks, 2 rows, 3 columns
print(arr3.ndim)    # 3 → 3D array

# Accessing elements
print(arr3[0, 1, 2])   # 6 → block 0, row 1, column 2
print(arr3[1, 0, 1])   # 8 → block 1, row 0, column 1


In [2]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr.shape) # tells the shape of the array
print(arr.ndim) # tells the number of dimensions
print(arr.size) # tells the total number of elements in the array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
12


In [3]:
# printing the array elements
print(arr[0, 1, 2]) # prints the element at index [0][1][2] which is 6

6


# ✂️ Slicing in 3D Arrays

## 📖 Definition
- **Slicing** allows you to access **multiple elements** of a NumPy array at once.
- In a **3D array**, slicing works across **blocks (groups), rows, and columns**.

---

## 🧩 Syntax
```python
arrayname[group, row_slice, col_slice]


In [3]:
print(arr[0:, 0:, 0:]) # prints all elements in the array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
print(arr[0, :, :]) # prints all elements in the first 2D array

[[1 2 3]
 [4 5 6]]


In [6]:
print(arr[:, 0, :]) # prints all elements in the first 2D array along the second axis

[[1 2 3]
 [7 8 9]]


In [8]:
print(arr[:, :, 0]) # prints all elements in the first 2D array along the third axis

[[ 1  4]
 [ 7 10]]


# 🌟 Special Types of Arrays in NumPy

## 📖 Overview
NumPy provides functions to quickly create arrays with predefined values such as zeros, ones, a constant value, or an identity matrix.

---

## 🧩 Examples

```python
import numpy as np

# 1. Zeros Array → array filled with 0s
zeros_arr = np.zeros((3, 4))
print("Zeros Array:\n", zeros_arr)

# 2. Ones Array → array filled with 1s
ones_arr = np.ones((2, 3))
print("\nOnes Array:\n", ones_arr)

# 3. Full Array → array filled with a specific value
full_arr = np.full((2, 2), 7)
print("\nFull Array:\n", full_arr)

# 4. Identity Matrix → square matrix with 1s on diagonal
identity_mat = np.eye(3)
print("\nIdentity Matrix:\n", identity_mat)


# 🟦 Identity Matrix in NumPy

## 📖 Definition
- An **identity matrix** is a square matrix with:
  - `1`s on the main diagonal
  - `0`s everywhere else
- Commonly used in **linear algebra** and matrix operations.

---

## 🧩 Example

```python
import numpy as np

# Using np.eye()
identity_mat = np.eye(3)
print(identity_mat)
# Output → 3x3 identity matrix

# Using np.identity()
a4 = np.identity(5, dtype=int)
print(a4)
# Output → 5x5 identity matrix with integer type


# 🔄 Reshape in NumPy

## 📖 Definition
- `reshape` is a method in NumPy used to **change the shape of an array** without changing its data.
- It reorganizes the elements into a new dimension structure.

---

## 🧩 Syntax
```python
array.reshape(new_shape)

- new_shape → tuple defining the desired dimensions.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape into 2 rows × 3 columns
reshaped = arr.reshape(2, 3)
print(reshaped)
# Output:
# [[1 2 3]
#  [4 5 6]]

```
---
# Rules of Reshape
## 1. Total elements must remain the same
    - Example: 1D array with 6 elements → can reshape to (2, 3) or (3, 2), but not (2, 4).


In [9]:
y_reshape = arr.reshape(3, 4) # reshapes the array to 3 rows and 4 columns
print(y_reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# 🔢 np.arange()

## 📖 Definition
- `np.arange()` is used to create a **sequence of numbers** with a fixed step size.
- Similar to Python’s built-in `range()`, but returns a **NumPy array**.

---

## 🧩 Syntax
```python
np.arange(start, stop, step)
- start → beginning of the sequence (default = 0)
- stop → end of the sequence (exclusive)
- step → difference between consecutive numbers (default = 1)

import numpy as np

# Sequence from 0 to 9
arr1 = np.arange(10)
print("arr1:", arr1)

# Sequence from 2 to 9
arr2 = np.arange(2, 10)
print("arr2:", arr2)

# Sequence with step size
arr3 = np.arange(1, 10, 2)
print("arr3:", arr3)

# Sequence with custom step
arr4 = np.arange(0, 20, 5)
print("arr4:", arr4)


# ndim()
## It is parameter which is used to define the dimension while creating an array.

In [12]:
a1 =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], ndmin=2) # creates a 2D array with 1 row and 10 columns
print(a1)
print(a1.ndim) # tells the number of dimensions


[[ 1  2  3  4  5  6  7  8  9 10]]
2


In [ ]:
# difference between ndim and ndmin

# ndim = parameter and we will tell what dimension we want while creating the array.
# adim = attribut it will just show the dimension of the array.
